### ISSUE TITLE
Prepare Release 10.2.2.0

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#200]
#### Checklist (after the release has been done on the `khiops` repository; see https://github.com/KhiopsML/khiops/issues/322):
- [x] Create branch
- [x] Update CHANGELOG.md
- [x] Update `DEFAULT_KHIOPS_REVISION` in [.github/workflows/dev-docker.yml] to 10.2.2
- [x] Update `DEFAULT_KHIOPS_CORE_VERSION` in [.github/workflows/conda.yml] to 10.2.2
- [x] Push this issue branch and create PR for it
- [x] Launch [.github/workflows/dev-docker.yml] manually to update the development Docker images to the 10.2.2 Khiops core packages; make sure that:
   - Khiops core version is set to 10.2.2
   - The choice to push the images to the GitHub registry is checked. 
- [ ] Merge PR into `dev`
- [ ] Create PR to merge `dev` into `main`;
- [ ] Merge PR into `main`;
- [ ] Git tag `main` with 10.2.2.0;
- [ ] Push the 10.2.2.0 tag on `main`;
- [ ] Launch [.github/workflows/pip.yml] and [.github/workflows/conda.yml] manually, on the 10.2.2.0 tag; thusly, the Conda packages are pushed on the default `khiops-dev` channel;
- [ ] Launch [.github/workflows/conda.yml] manually, on the 10.2.2.0 tag, selecting the official `khiops` channel;
- [ ] Copy relevant CHANGELOG.md contents to the 10.2.2.0 GitHub pre-release;
- [ ] Launch [.github/workflows/api-docs.yml] manually on the 10.2.2.0 tag and instruct it to deploy the documentation pages;
- [ ] Transform the 10.2.2.0 GitHub pre-release into a release.
